#!/bin/bash

# Safety check: Ensure the user provided at least one thread count
if [ "$#" -eq 0 ]; then
    echo "Error: No thread count provided."
    echo "Usage: bash script/task1_POSIX_N.sh <thread_count1> [thread_count2 ...]"
    echo "Example: bash script/task1_POSIX_N.sh 2 4 8 32"
    exit 1
fi

# Lock onto the exact directory your terminal is in
BASE_DIR=$(pwd)
PROGRAM="$BASE_DIR/compile/task1_POSIX"

# Ensure the 'time' folder exists
mkdir -p "$BASE_DIR/time"
CSV_FILE="$BASE_DIR/time/task1_POSIX_N.csv"

# Append to the CSV if it exists, or create it with headers if it doesn't
if [ ! -f "$CSV_FILE" ]; then
    echo "N,Threads,Computational_Time_sec,Overall_Time_sec" > "$CSV_FILE"
fi

echo "Starting POSIX Benchmark..."

# OUTER LOOP: Loop through every thread count passed via command line
for THREADS in "$@"
do
    echo "--------------------------------------------------------"
    echo "Starting tests for THREADS = $THREADS"
    echo "--------------------------------------------------------"
    
    # INNER LOOP: Loop through values of N
    for N in $(seq 10000000 1000000 40000000)
    do
        # Run the C program directly using Mode 2 (Passing variables directly)
        OUTPUT=$("$PROGRAM" $N $THREADS)
        
        # Extract the numerical time values using grep and awk
        COMP_TIME=$(echo "$OUTPUT" | grep "Computational Time:" | awk '{print $3}')
        OVERALL_TIME=$(echo "$OUTPUT" | grep "Overall Time:" | awk '{print $3}')
        
        # Print progress to the terminal
        echo "Tested N = $N | Threads: $THREADS | Comp: $COMP_TIME s | Overall: $OVERALL_TIME s"
        
        # Append the extracted data to the master CSV file
        echo "$N,$THREADS,$COMP_TIME,$OVERALL_TIME" >> "$CSV_FILE"
    done
done

# Clean up ONLY the final text file generated by the C program
rm -f task1_POSIX.txt

echo "--------------------------------------------------------"
echo "Benchmarking complete! Data saved to $CSV_FILE."